######################################################################
# Automatically generated by qmake (3.0) ?? ????? 18 23:53:58 2014
######################################################################
QT       += core gui widgets
TEMPLATE = app
TARGET = Polygon
INCLUDEPATH += .

# Input
HEADERS += \
           drawpanel.h \
           mainwindow.h \
    mqpainter.h
SOURCES += \
           drawpanel.cpp \
           main.cpp \
           mainwindow.cpp \
    mqpainter.cpp
